dist: xenial

before_install:
  - sudo apt-get update
  - sudo apt-get install -y git ant cmake openjdk-8-jdk g++ mongodb python

script:
  - export JAVA_HOME=$(dirname $(dirname $(readlink -f $(which javac))))
  - cd danhelper
  - mkdir build
  - cd build
  - cmake ..
  - make
  - cd ../../danalyzer
  - ant
  - cd ../dansolver
  - ant
  - cd ../danlauncher
  - ant

