os:
  - linux
  - osx

services: mongodb

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update; sudo apt-get install -y git ant cmake openjdk-8-jdk g++ jq wget unzip; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; brew install git ant cmake openjdk-8-jdk g++ jq wget unzip mongodb; brew services start mongodb; fi

script:
  - export JAVA_HOME=$(dirname $(dirname $(readlink -f $(which javac))))
  - cd danhelper
  - mkdir build
  - cd build
  - cmake ..
  - make
  - cd ../../danalyzer
  - ant
  - cd ../dansolver
  - ant
  - cd ../danlauncher
  - ant
  - cd ../
  - mkdir z3
  - cd z3
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget https://github.com/Z3Prover/z3/releases/download/z3-4.8.4/z3-4.8.4.d6df51951f4c-x64-ubuntu-16.04.zip; unzip z3-4.8.4.d6df51951f4c-x64-ubuntu-16.04.zip; cd z3-4.8.4.d6df51951f4c-x64-ubuntu-16.04/bin; sudo cp z3 libz3java.so libz3.so com.microsoft.z3.jar /usr/local/lib; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then wget https://github.com/Z3Prover/bin/raw/master/nightly/z3-4.8.5.eae4fd6afd29-x64-osx-10.11.6.zip; unzip z3-4.8.5.eae4fd6afd29-x64-osx-10.11.6.zip; cd z3-4.8.5.eae4fd6afd29-x64-osx-10.11.6/bin; cp z3 libz3java.dylib libz3.dylib com.microsoft.z3.jar /usr/lib; fi
  - cd ../../../dansolver
  - ant run &
  - cd ../tests
  - ./make_tests.sh ByteRangeTest
  - ./run_tests.sh ByteRangeTest
